### ISSUE TITLE
Projectile Collision neutralisation over common tile

### ISSUE THREAD

**Issue by m1kboi** [malamunyx/gremlins-mik#1]
## Issue
Two projectiles become neutralised when colliding the same wall on opposite sides.
## Expected Behaviour
If colliding over brick wall, it becomes destroyed given fireball collides first, or slime collides first as fireballs are the only projectile to have the capacity to interact with walls and change their states.
## Proposal for fix
- [ ] Projectile collisions must handle collisions with neutralised projectiles, ignoring them. Update the spriteCollision functions for all sprites implementing Projectile interfaces.

**Comment by malamunyx** [comment]
archiving repo.
